### ISSUE TITLE
bug mysql driver version

### ISSUE THREAD

**Issue by sdcuike** [mybatis/generator#143] opened 2016-09-01 07:45 UTC
mysql-connector-java-5.1.6,and 6.0.3 have errror: Column 'IS_GENERATEDCOLUMN' not found

when use  \mysql-connector-java-5.1.39.jar"  no error .

#  Use:MyBatis Generator Release 1.3.4 version

**Comment by jeffgbutler** [comment] 2016-09-01 11:29
This is a duplicate of #136.  If you can use a JDBC driver that supports JDBC version 4.1 it should work.  I'll get a new release out hopefully over the weekend.

**Closed by jeffgbutler** 2016-09-01 11:29 UTC
