### ISSUE TITLE
Table remarks in DatabaseIntrospector

### ISSUE THREAD

**Issue by a-n-ermakov** [mybatis/generator#23] opened 2014-09-25 09:13 UTC
Hello!

I want to add comments,stored in REMARKS in DB, to java model classes. It's easy for COLUMNS, for example, using introspectedColumn.getRemarks() in addFieldComment.

But for TABLES, there is no field 'remarks', because DatabaseIntrospector don't extract such information from DatabaseMetaData.

Can you add such functionality to generator? It's very useful, when developer has commented java model.

Best regards,

Anton

**Comment by wuzhaozhongguo** [comment] 2015-06-24 06:58
+1

**Comment by jloyolask8** [comment] 2015-09-09 17:15
I need this as well. any workaround to this??

Regards

**Comment by a-n-ermakov** [comment] 2015-09-14 08:51
>>> I need this as well. any workaround to this??

Only patch

**Comment by jloyolask8** [comment] 2015-09-14 14:15
Can you share this patch?

**Comment by jeffgbutler** [comment] 2015-09-14 14:25
Currently, the generator doesn't call the getTables() function in DatabaseMetaData, so it's not just a simple change.  I'll take a look at what it would take to get this done, but it's probably not a quick fix given the limited time I have for this right now.

**Comment by jacarrichan** [comment] 2015-09-15 07:10
I have a idea to fix this problem.

The java file at 
https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/internal/DefaultCommentGenerator.java

about the method of "addFieldComment",

remove above code:
```java
         field
                 .addJavaDocLine(" * This field was generated by MyBatis Generator."); //$NON-NLS-1$
 
         sb.append(" * This field corresponds to the database column "); //$NON-NLS-1$
         sb.append(introspectedTable.getFullyQualifiedTable());
         sb.append('.');
         sb.append(introspectedColumn.getActualColumnName());
         field.addJavaDocLine(sb.toString());

```

and instead of this code:

```java
field.addJavaDocLine(" * "+introspectedColumn.getRemarks()); //$NON-NLS-1$
```

#  I  have no time to write a unit test about this idea, so i don't send a PR.

**Comment by a-n-ermakov** [comment] 2015-09-15 07:58
jeffgbutler,

for now, i created a PR #43 with RemarksCommentGenerator for support field comments. Can you accept it? I will be able to support comments for table in future, when changes in DatabaseIntrospector will be available.

**Comment by a-n-ermakov** [comment] 2015-09-15 07:59
> jloyolask8

sorry, but i use only field comments. I not patched generator for table comments.

**Comment by jeffgbutler** [comment] 2015-09-15 19:12
I've pushed a fix for this.  Give it a try and let us know if it works as you expect.  Note that the fix just adds the remarks (and table type) to the IntrospectedTable.  You will still need to write your own code to use that data at this point - although I suspect that @a-n-ermakov will enhance the pull request for #43 to use this new data.

**Closed by jeffgbutler** 2015-09-15 19:12 UTC

**Comment by jloyolask8** [comment] 2015-09-15 20:06
I did write a custom CommentGenerator, that uses 

field.addJavaDocLine(" * "+introspectedColumn.getRemarks()); //$NON-NLS-1$

But the problem is that the method introspectedColumn.getRemarks() does not bring the comments.

Can you confirm that this was included in this fix?

Regards

**Comment by jeffgbutler** [comment] 2015-09-15 20:09
Table remarks will be in introspected**Table**.getRemarks()

**Comment by jloyolask8** [comment] 2015-09-15 20:11
Well, that is owesome. but this issue im facing is that the introspectedColumn always brings null for getRemarks().

Do you consider this as a bug? or maybe im doing something wrong?

Regards

**Comment by jeffgbutler** [comment] 2015-09-15 20:34
The remarks fields are filled from the REMARKS properties returned in getColumns() and getTables() methods in DatabaseMetaData.  I'm pretty confident introspectedColumn.getRemarks() works because I'm using it on a project.

So a couple of things could be happening:

1. Your JDBC driver might not be returning the remarks
2. There might not be remarks associated with the column you are interested in

What DB/Driver are you using?

**Comment by jloyolask8** [comment] 2015-09-15 20:55
Im using Oracle Database 11g Enterprise Edition Release 11.2.0.2.0
Specification-Version: Oracle JDBC Driver version - "11.1.0.7.0-Production"

Im sure the remarks are in the column.

**Comment by a-n-ermakov** [comment] 2015-09-15 21:01
I'll rework standard comment generator with properties to add remarks to fields and tables in PR #43, possible in 1-2 days

**Comment by jeffgbutler** [comment] 2015-09-15 21:05
I just did a little test with HSQLDB and I got both table and column remarks back.  The SQL syntax for adding remarks to the table and column was a little strange in HSQLDB.

I guess I'd suggest writing a little straight JDBC test to see if the remarks come back.

**Comment by wushp** [comment] 2016-06-26 00:32
thanks!

**Comment by liunewshine** [comment] 2017-08-04 14:15
@jeffgbutler remarks from introspected table always return '' .
I use mysql 5.1.43
mybatis-generator-core 1.3.5
