### ISSUE TITLE
ResultSet can't find  IS_GENERATEDCOLUMN

### ISSUE THREAD

**Issue by chouway** [mybatis/generator#148] opened 2016-09-06 16:37 UTC
mybatis-generator-maven-plugin:1.3.4:generate (default-cli) on project base-api: ResultSet can't find IS_GENERATEDCOLUMN.

my driveClass :  postgresql.9.4.1209.jre7 .

it seems that some db driver don't provide the DataMeta of IS_GENERATECOLUMN.

by the way, I  turn it to mybatis-generate-maven-plugin:1.3.2 , the project can work well .

**Comment by jeffgbutler** [comment] 2016-09-06 17:16
Duplicate of #136

**Closed by jeffgbutler** 2016-09-06 17:16 UTC

**Comment by chouway** [comment] 2016-09-07 01:14
Tks
