### ISSUE TITLE
domainObjectRenamingRule problem

### ISSUE THREAD

**Issue by linchuyao** [mybatis/generator#514] opened 2019-11-16 09:39 UTC
version 1.3.7 
mysql table name user_login_log   
when i config domainObjectRenamingRule whth ^User geberator result:  Loginlog  not CamelCaseString version 1.3.6 not problem

if (domainObjectRenamingRule != null) {
            Pattern pattern = Pattern.compile(domainObjectRenamingRule.getSearchString());
            String replaceString = domainObjectRenamingRule.getReplaceString();
            replaceString = replaceString == null ? "" : replaceString; //$NON-NLS-1$
            Matcher matcher = pattern.matcher(finalDomainObjectName);
            finalDomainObjectName = getCamelCaseString(matcher.replaceAll(replaceString), true); ??????
        }

**Comment by jeffgbutler** [comment] 2019-11-16 15:46
Duplicate of #382

**Closed by jeffgbutler** 2019-11-16 15:46 UTC
Labels: duplicate
