### ISSUE TITLE
mybatis-generator-core -> org.mybatis.generator.internal.util.StringUtility

### ISSUE THREAD

**Issue by iamgoodmanm** [mybatis/generator#353] opened 2018-05-15 09:12 UTC
in StringUtility.
![default](https://user-images.githubusercontent.com/17421499/40046422-87104798-585f-11e8-8d91-c53f0b3e2544.png)

now my params:
catalog="test"
schema=null
tableName="my_test"
separator='.'

result:
test..my_test
there are two dots!

this may lead to generate error sql. like this:
in generatorConfig.xml
`<table tableName="my_test" domainObjectName="myTest" catalog="test"/>`

and in MyTestMapper.xml
![default](https://user-images.githubusercontent.com/17421499/40047617-8438e874-5862-11e8-9169-ecf13d478259.png)

Please help me to solve it. 
Thank you！

**Comment by jeffgbutler** [comment] 2018-05-15 10:00
Duplicate of #334 and #17. Please read the documentation about how to configure the generator for MySQL.

**Closed by jeffgbutler** 2018-05-15 10:00 UTC
