### ISSUE TITLE
How to keep Java model name using Camel Case in V1.3.7?

### ISSUE THREAD

**Issue by diguage** [mybatis/generator#421] opened 2018-10-28 03:42 UTC
How to keep Java model name using Camel Case in 1.3.7?

`table` tag configuration is as following:

```xml
<table tableName="%">
    <generatedKey column="id" sqlStatement="Mysql" identity="true" type="post"/>
    <domainObjectRenamingRule searchString="^T" replaceString=""/>
</table>
```

**Comment by jeffgbutler** [comment] 2018-10-28 11:07
This is a duplicate of #381 (fixed, but not released yet).

**Closed by jeffgbutler** 2018-10-28 11:07 UTC

**Comment by diguage** [comment] 2018-10-29 01:30
How to configure it?

**Comment by jeffgbutler** [comment] 2018-10-29 09:45
There is a bug in 1.3.7. If you use the 1.4.0-SNAPSHOT version it should work. You can read about configuring maven to access the snapshot releases here: https://github.com/mybatis/mybatis-3/wiki/Maven

**Comment by diguage** [comment] 2018-10-30 09:16
@jeffgbutler 
Thanks. I thought it add new configuration option. Sorry.
