### ISSUE TITLE
Collection instead of List

### ISSUE THREAD

**Issue by activekou** [mybatis/generator#638] opened 2020-10-14 12:52 UTC
![image](https://user-images.githubusercontent.com/24381124/95991182-0c8a3c00-0e5f-11eb-91dc-9b3054464bf8.png)
 the param maybe  Set<Long>

**Comment by jeffgbutler** [comment] 2020-10-14 13:14
Duplicate of #483

**Closed by jeffgbutler** 2020-10-14 13:14 UTC
Labels: duplicate, wontfix
