### ISSUE TITLE
the generated content of xml file will be appended at xml file

### ISSUE THREAD

**Issue by zhouhongjian** [mybatis/generator#196] opened 2017-02-25 13:50 UTC
When I use mybatis-generator-maven-plugin whose version is 1.3.2 or 1.3.5 to generate code  more than once,the genetated content of xml file will append xml file , even if I set overwrite is true.But the action is overwrite when I use the plugin whose version is 1.3.0 more than once. I think  that append content  of xml file at tail of xml file is not right in the new version.
ps:
IDE is Intellj IDEA 2016.2.2 
maven version is 3.3.9     
Java version is 1.8.0
OS is Win10

**Comment by chenweiwei417** [comment] 2017-02-26 06:38
The Same problem

**Comment by jeffgbutler** [comment] 2017-02-26 16:25
The overwrite property is only used for generated Java files.  It should not affect XML files at all.  XML files should always be merged.

Have you configured a comment generator with suppressAllComment=true?  If so, that would be the cause of this behavior.  The XML merge won't delete old elements if the comments are removed.

**Comment by MuhammadHuzaifah** [comment] 2017-02-27 09:05
@jeffgbutler see my comment here #82

**Comment by jeffgbutler** [comment] 2017-02-27 10:21
Thanks.  I asked the same question...do you have suppressAllComments=true?

**Comment by zhouhongjian** [comment] 2017-02-27 11:49
Yes,I have  suppressAllComments=true. And I try removing the property,then mybatis-generator whose version is 1.3.2 and 1.3.5 is normal to regenerate xml file. Thanks. @jeffgbutler 

But I think I don't need the autogenerated comments because they are similar. And I don't understand that the problem is related to suppressAllComments .

**Comment by jeffgbutler** [comment] 2017-02-27 11:55
The merge works by deleting the prior version of generated code.  The merger uses the comments to determine what can be deleted. If you are trying to avoid extra source control commits when things haven't really changed, then use this:

```xml
<commentGenerator>
  <property name="suppressDate" value="true"/>
</commentGenerator>
```

**Comment by zhouhongjian** [comment] 2017-02-27 13:03
In other word, if <select>...</select> has not comments,it won't be deleted when I regenerate code.
Also,if I have suppressAllComments=false,I can add extra code to xml file instead of creating a new xml file to write the extra code. 
When I used mybatis-generator whose version is 1.3.0 , the suppressAllComments is invalid. It must generate comments. So suppressAllComments is a new feature and it isn't suitable for regenerating code.
Is it true?

**Comment by zhouhongjian** [comment] 2017-02-27 13:05
... is `<select>...</select>`.

**Comment by jeffgbutler** [comment] 2017-02-27 13:55
This was added in version 1.31 - six years ago.  So I don't really think of it as new feature.  Also, it is documented on the comment generated manual page that using it will disable code merging.

http://www.mybatis.org/generator/configreference/commentGenerator.html

**Closed** 2017-02-27 14:13 UTC
Labels: question

**Comment by icanfly** [comment] 2017-12-29 15:31
The same problem. Really hate the  function to merge .

**Comment by jeffgbutler** [comment] 2017-12-29 16:51
I will add a plugin to disable merging of the XML files.  There seems to be a lot of confusion about this.
