### ISSUE TITLE
Sample Configuration issue

### ISSUE THREAD

**Issue by lovejuan2008** [mybatis/generator#784] opened 2021-12-12 12:43 UTC
<img width="1435" alt="截屏2021-12-12 20 24 03" src="https://user-images.githubusercontent.com/55969113/145712478-9e6beb5a-667d-41ee-9872-e81415341b93.png">
TargetRuntime Sample Configuration for MyBatis3 and MyBatis3Simple is same,it would be a trouble for learner

**Comment by jeffgbutler** [comment] 2021-12-18 15:47
Duplicate of #572

**Closed by jeffgbutler** 2021-12-18 15:47 UTC
