### ISSUE TITLE
domainObjectRenamingRule not work

### ISSUE THREAD

**Issue by LzhBruce** [mybatis/generator#536] opened 2020-01-05 08:28 UTC
when I use domainObjectRenamingRule config in table label, the result not What I want.
table name is "per_unit_machine", Object name is "PerUnitMachine". When I use domainObjectRenamingRule param. 
the new domain name is "Unitmachine", not "UnitMachine" that I want.
mybatis-generator-core version is 1.3.7

detail info :
<domainObjectRenamingRule searchString="^Per" replaceString=""/>

**Comment by jeffgbutler** [comment] 2020-01-05 12:23
This has been fixed in version 1.4.0 - please upgrade to the new version.

Duplicate of #381.

**Closed by jeffgbutler** 2020-01-05 12:23 UTC

**Comment by LzhBruce** [comment] 2020-01-09 09:48
thanks.
