### ISSUE TITLE
Enforce Formatting at 4 spaces matching repo style

### ISSUE THREAD

**Issue by hazendaz** [mybatis/generator#237] opened 2017-05-27 18:36 UTC
In mybatis-parent 29, checkstyle has been added.  As a result, checkstyle results for this module set are rather high.  Roughly 19K of that is violation of the standard mybatis 2 character spacing requirement.  I can fix this by adding a marker 'format.xml' file into the repo.  However, this will be encredibly noisey.  Beyond being noisey, we would have to wait until all outstanding PRs are addressed.

**Comment by hazendaz** [comment] 2017-05-27 18:37
Details from checkstyle for this...

 	Indentation

    throwsIndent: "4"
    arrayInitIndent: "2"
    caseIndent: "2"
    basicOffset: "2"
    braceAdjustment: "0"
    lineWrappingIndentation: "4"

	19521 	 Warning

**Comment by jeffgbutler** [comment] 2017-05-27 19:09
Yeah - please don't do this.  The modules can choose their own formatting standards.

**Comment by hazendaz** [comment] 2017-05-27 23:43
Ok I'll adjust rules for checkstyle on this module instead.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment] 2017-05-28 21:29
In alignment with this repo, I have made changes to override that of mybatis-parent to setup for expectation of 4 character spacing.  As a result, when applied, generalized fixes (ie trailing spaces and invalid alignment) are fixed to less extent hitting 125 files on core module.  I have not looked at others yet.  I'll submit a PR but let you review and look at it.  It's mostly removal of trailing spaces.  At this point, making this an automatic feature isn't yet possible as there are additional formatting considerations I still need to review.  However, this can be ocassionally owner checked rather than part of the build and in that probably not very often.

**Comment by jeffgbutler** [comment] 2017-05-30 21:01
I made a few changes to checkstyle.xml:

1. let the line length be up to 120.  This removed a lot of Javadoc warnings (not all, but I think 120 is reasonable)
2. Do not require a blank line between the license header and the package declaration.  This will stop issues caused by the license plugin.
3. Allow some acronyms of up to 4 characters in method names
4. Don't require Javadoc on all methods

There's still a lot of noise in the checkstyle report, but it's getting less crazy.

**Comment by hazendaz** [comment] 2017-05-31 02:12
Most of that sounds reasonable to go up to parent level and ignore google.  With 1, I've always felt 120 is reasonable.  With 2, that is primarily the issue across nearly all the repos I've gotten through looking at so far within mybatis domain.  With 3, that makes sense as it was very limiting and not something to fix in all cases.  Then with 4, I'm not even sure it was very coherant in its consideration for what needed javadocs.  It seemed to potentially have issues with that.  Generally I take the all approach with javadocs using a generator so I hadn't noticed before that area of the checkstyle might not quite be right.  Some publics it didn't seem to care about.  Anyways, awesome job clearing those! I'll definitely use these leasons learned when it comes to the core as I'm sure what is on the surface isn't reality ;)

**Comment by jeffgbutler** [comment] 2017-05-31 09:48
I made one more change related to formatting switch/case.

I don't often write javadocs, but when I do they actually mean something :)

**Comment by jeffgbutler** [comment] 2017-08-05 16:02
Closing because this work has been completed.

**Closed by jeffgbutler** 2017-08-05 16:02 UTC
