### ISSUE TITLE
XXXexample should support null or empty object

### ISSUE THREAD

**Issue by rockethj** [mybatis/generator#352] opened 2018-05-09 15:53 UTC
When I add a null value or empty string value to example criteria, I expect should not generate related sql. However current generated example will throw RuntimeException. 

Totally understand somebody need this exception, So can I add an optional configuration this feature?

 protected void addCriterion(String condition, Object value, String property) {
            if (value1 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

**Comment by jeffgbutler** [comment] 2018-05-09 18:16
Duplicate of #204 

This feature is resolved in a systematic way with the new MyBatis Dynamic SQL runtime. I do not plan to update the legacy code generators.

**Closed** 2018-05-19 12:38 UTC
Labels: duplicate, question
