### ISSUE TITLE
appoint my schema, it will read other schema

### ISSUE THREAD

**Issue by OrangesHuang** [mybatis/generator#272] opened 2017-08-15 05:11 UTC
![image](https://user-images.githubusercontent.com/13177793/29302934-03630974-81bb-11e7-8da1-0950208425e8.png)
this my generator.xml tableName="%" schema="auth2_relation"
auth2_relation is my schema
![image](https://user-images.githubusercontent.com/13177793/29302901-b222568c-81ba-11e7-835a-15a1ddb80045.png)
but when i run , it want to read View 'sys.host_summary'
![image](https://user-images.githubusercontent.com/13177793/29302921-e3e038f6-81ba-11e7-8240-c09b98782189.png)

**Comment by jeffgbutler** [comment] 2017-08-15 14:37
Duplicate of #270

**Closed by jeffgbutler** 2017-08-15 14:37 UTC
Labels: duplicate
